[wip] refact-1_6B-fim finetune
smallcloudai/refact pull request #100
Opened 2023-09-08 16:16 UTC by JegernOUTT

Add basic possibility to finetune the model
Much work is ahead

2023-09-15 11:51 UTC, mitya52 requested changes

2023-09-15 11:51 UTC, mitya52 commented on refact_data_pipeline/finetune/finetune_config.py
> +MODELS_CONFIGS = {
lets separate configs and code

2023-09-15 11:51 UTC, mitya52 commented on refact_data_pipeline/code_filter.py
> +from kshingle import shingleseqs_list
please check all new imports and update setup.py

2023-09-19 05:03 UTC, olegklimov approved these changes

2023-09-19 05:11 UTC, merged