Lora upload
smallcloudai/refact pull request #136
Opened 2023-09-28 17:28 UTC by valaises

2023-10-04 08:53 UTC, olegklimov approved these changes
Good changes, but I didn't test yet.

2023-10-04 08:54 UTC, olegklimov commented
@valaises change destination to `dev` pls

2023-10-06 19:43 UTC, hazratisulton requested changes
Tried upload by link even with set name manually:
![image](https://github.com/smallcloudai/refact/assets/140423660/b4973584-fcc2-4e87-901e-bb03efd368cd)
![image](https://github.com/smallcloudai/refact/assets/140423660/35b9dbb2-84dd-466e-b131-b69978156e3b)
Tried upload from local zip file - worked.

2023-10-09 16:31 UTC, olegklimov commented on refact_data_pipeline/finetune/process_uploaded_files.py
> +        subprocess.check_call(cmd)
shutil

2023-10-09 16:33 UTC, olegklimov commented on self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
> +    submit_event(submit_link_endpoint, submit_input_endpoint, text_on_progress_done) {
add_submit_handler

2023-10-09 16:36 UTC, olegklimov commented on self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
> +    process_now_update_until_finished(upload_method) {
prepare_for_upload

2023-10-09 16:38 UTC, olegklimov commented on self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
> +                            file_modal.querySelector('#updlg-upload-files-status').innerHTML = error.message;
innerText

2023-10-09 16:43 UTC, olegklimov commented on self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
> +                data => {
indent

2023-10-09 16:44 UTC, olegklimov commented on self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
> +                    }).catch(
check if it catches errors in both blocks of code

2023-10-09 16:45 UTC, olegklimov commented on self_hosting_machinery/webgui/static/tab-upload.js
> +    document.querySelector('#upload-files-modal').innerHTML = "";
symmetric

2023-10-09 16:45 UTC, olegklimov commented on self_hosting_machinery/webgui/tab_loras.py
> +        log(f"Error while removing {f}: {e}")
shutil

2023-10-09 16:46 UTC, olegklimov commented on self_hosting_machinery/webgui/tab_upload.py
> +        raise e
raise

2023-10-09 16:49 UTC, olegklimov commented on self_hosting_machinery/webgui/tab_upload.py
> +            return JSONResponse({"message": f"Cannot download: {e}"}, status_code=500)
"detail"

2023-10-09 16:49 UTC, olegklimov commented on self_hosting_machinery/webgui/static/components/modals/modal-upload-files.js
> +function makeModalBackdropStatic() {
snake

2023-10-09 16:50 UTC, olegklimov commented on self_hosting_machinery/webgui/tab_loras.py
> +        return JSONResponse({"message": f"Error while unpacking: File {file_path.name} is not an archive; try setting filename manually"}, status_code=400)
"detail"

2023-10-09 16:50 UTC, olegklimov commented on self_hosting_machinery/webgui/tab_loras.py
> +            return JSONResponse({"message": f"Cannot download: {e}"}, status_code=500)
"detail"

2023-10-09 17:00 UTC, olegklimov commented
`file xxxxxxx --mime-type --brief`

2023-10-11 08:27 UTC, merged