rh-stats handler for dashboard-in-rust
smallcloudai/refact pull request #291
Opened 2024-02-02 18:39 UTC by valaises

2024-02-05 13:08 UTC, mitya52 requested changes

2024-02-05 13:08 UTC, mitya52 commented on self_hosting_machinery/webgui/selfhost_statistics.py
> +            prep = self._stats_service.session.prepare(
why do we use direct session call instead of requesting stats service?

2024-02-05 13:08 UTC, mitya52 commented on self_hosting_machinery/webgui/selfhost_statistics.py
> +        self.add_api_route('/rh-stats', self._rh_stats, methods=["POST"])
this route should use authorization

2024-02-07 19:20 UTC, mitya52 commented on self_hosting_machinery/webgui/selfhost_statistics.py
>          self.add_api_route("/telemetry-snippets", self._telemetry_snippets, methods=["POST"])
do this two handlers require authorization?

2024-02-07 19:26 UTC, mitya52 approved these changes

2024-02-12 17:52 UTC, hazratisulton approved these changes

2024-02-12 19:17 UTC, merged