Dashboard Improvements
smallcloudai/refact pull request #316
Opened 2024-02-27 17:58 UTC by valaises

2024-02-28 17:36 UTC, mitya52 requested changes

2024-02-28 17:36 UTC, mitya52 commented on refact_webgui/dashboards/dash_prime.py
> +        "31 days": extract_stats(
365.25/12 = 30.43(6)
floor(30.43(6)) = 30

2024-02-28 17:36 UTC, mitya52 commented on refact_webgui/webgui/selfhost_database.py
> +        rh_df['dt_end'] = pd.to_datetime(rh_df['ts_end'], unit='s')
but why...next will be rh_df -> r

2024-02-28 18:47 UTC, mitya52 approved these changes

2024-03-01 18:15 UTC, hazratisulton approved these changes

2024-03-02 09:03 UTC, merged