Passthrough Mini DB
smallcloudai/refact pull request #398
Opened 2024-04-15 17:40 UTC by valaises

2024-04-16 16:39 UTC, valaises commented on known_models_db/refact_known_models/passthrough.py
> +        "filter_caps": ["chat"],
leave empty

2024-04-16 16:39 UTC, valaises commented on known_models_db/refact_known_models/passthrough.py
> +        "provider": "openai",
add backend

2024-04-16 16:43 UTC, valaises commented on refact_utils/finetune/utils.py
> +        [add_result(k, {'has_chat': True}) for k, v in passthrough_mini_db.items() if v.get('provider') == 'openai' and 'chat' in v.get('filter_caps', [])]
make a function instead

2024-04-16 16:49 UTC, valaises commented on refact_webgui/webgui/selfhost_model_resolve.py
> +def resolve_model_context_size(model_name: str) -> Optional[int]:
use model_assigner

2024-04-16 16:50 UTC, valaises commented on refact_webgui/webgui/selfhost_model_resolve.py
> +def resolve_model_context_size(model_name: str) -> Optional[int]:
no imports from known_models_db!

2024-04-16 16:56 UTC, valaises commented on refact_webgui/webgui/selfhost_queue.py
> -            if j.get("openai_api_enable", False):
pass model_assigner to InferenceQueue

2024-04-16 16:56 UTC, valaises commented on known_models_db/refact_known_models/passthrough.py
> +        "filter_caps": ["chat"],
mb remove?

2024-04-16 16:57 UTC, valaises commented on known_models_db/refact_known_models/passthrough.py
> +        "T_out": 4096,
pass it to litellm as param

2024-04-16 20:22 UTC, valaises commented on known_models_db/refact_known_models/passthrough.py
> +        "filter_caps": ["chat"],
Cannot remove. It's used in running_models_and_loars at finetune/utils.py

2024-04-17 15:39 UTC, mitya52 requested changes

2024-04-17 15:39 UTC, mitya52 commented on refact_utils/finetune/utils.py
> +        ]
* add_results_for_passthrough_provider -> _add_results_for_passthrough_provider
* write without list comprehension
* all passthrough models are about chat so no need in add_result usage here

2024-04-17 15:39 UTC, mitya52 commented on refact_utils/finetune/utils.py
> +        ]
...and "chat" caps checking

2024-04-17 15:39 UTC, mitya52 commented on refact_webgui/webgui/selfhost_fastapi_completions.py
> +from refact_webgui.webgui.selfhost_model_resolve import completion_resolve_model, resolve_model_context_size, resolve_tokenizer_name_for_model
3 separate imports please

2024-04-17 15:39 UTC, mitya52 commented on refact_webgui/webgui/selfhost_fastapi_completions.py
> +            "n_ctx_rewrite": {model: t for model in models_available if (t := resolve_model_context_size(model, self._model_assigner))},
t -> n_ctx

2024-04-17 15:39 UTC, mitya52 commented on refact_webgui/webgui/selfhost_fastapi_completions.py
> +        if model_dict.get('backend') == 'litellm' and (model_name := model_dict.get('resolve_as', post.model)) in litellm.model_list:
no model_name if backend is not litellm
do not use := operator everywhere

2024-04-17 15:39 UTC, mitya52 commented on refact_webgui/webgui/selfhost_model_resolve.py
> +        return model_assigner.passthrough_mini_db[model_name].get('tokenizer')
tokenizer...do you mean tokenizer_path?

2024-04-17 17:17 UTC, mitya52 requested changes

2024-04-17 17:17 UTC, mitya52 commented on refact_webgui/webgui/selfhost_fastapi_completions.py
> +from known_models_db.refact_known_models import passthrough_mini_db
no need in this import

2024-04-17 17:17 UTC, mitya52 commented on refact_webgui/webgui/selfhost_queue.py
> +                self._models_available.extend(k for k, v in self._model_assigner.passthrough_mini_db.items() if v.get('provider') == 'anthropic')
same code, unify it

2024-04-17 17:36 UTC, mitya52 approved these changes

2024-04-17 18:39 UTC, merged