Server Logs Read Fix
smallcloudai/refact pull request #417
Opened 2024-05-03 16:04 UTC by valaises

2024-05-08 11:16 UTC, olegklimov commented
live streaming -n 1000 is a good idea

for plain file 50000 maybe is a good idea too

2024-05-10 08:49 UTC, mitya52 requested changes

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +    print(f"EXEC: {' '.join(cmd)}")
why print? we have logger if it really heeds the logging

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +    cmd = ["tail", f"-n {last_n_lines}", file_path]
is there a python package for this task?

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +    print(f"EXEC: {' '.join(cmd)}")
and is there a package for count lines in file?

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +            last_n_lines = 10_000
make it default parameter instead of var

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +            last_n_lines = 10_000
make it default parameter instead of var

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +                await f.seek(0, os.SEEK_END)
what is the purpose of this line? why we should go to the end of the file if we simply need to stream last n lines?

2024-05-10 08:49 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +                        yield line
this looks weird: you're streaming last lines with tail (on opened file!!!) and then read from file directly...

2024-05-10 14:24 UTC, mitya52 requested changes

2024-05-10 14:24 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +                async for line in atail(right_file):  # (line, from_file)
here we can loose some lines from working logs

2024-05-10 14:24 UTC, mitya52 commented on refact_webgui/webgui/tab_server_logs.py
> +                async for line in atail(right_file):  # (line, from_file)
inthe case of streaming it should work exactly as
tail -n last_n_lines -f logfile

2024-05-16 11:23 UTC, mitya52 commented
doesn't work correctly with
* non-existed file or non-file paths: stuck without exit
* stream=False doesn't work for regular log files, while loops forever

2024-09-20 17:44 UTC, closed without merging