Added White Refact Logo To ReadMe
smallcloudai/refact pull request #90
Opened 2023-09-05 11:42 UTC by miranamer

Makes it pop better against black bg.

2023-09-07 08:56 UTC, mitya52 requested changes
What about light theme?

2023-09-07 16:07 UTC, miranamer commented
what do you mean by light theme? the black logo? How would you change the logo based on the theme?

2023-09-07 16:23 UTC, miranamer commented
Added Logo Changes Based On Color Theme

2023-09-12 07:14 UTC, reymondzzzz approved these changes

2023-09-12 07:29 UTC, mitya52 approved these changes

2023-09-12 07:30 UTC, merged